apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: k8s
    repoURL: https://github.com/joisyousef/nodejs.org.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
