apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: joisyousef/nodejs-app
        ports:
        - containerPort: 3000
